### ISSUE TITLE
General form fixes

### ISSUE THREAD

**Issue by Mati0x** [1Hive/gardens-v2#106]
Ipfs:
- [x] only load to ipfs after preview and before submit transaction
- [x] dont let load to ipfs empty information (error preview handel)
- [x] improve submit button disabled state in signaling and funding create proposal 

Forms:
- [x]  for create proposal check spending limit
- [x]  not let submit button click without nothing happens

Pages:
- [x] create page for ProposalForm
- [x] create page for CommunityForm
 
Note: There was also a huge refactor of Form, Preview & Input components.

**Comment by kamikazebr** [comment]
Me and @pglavin2 we need test it
