### ISSUE TITLE
alpha-technical-fixes

### ISSUE THREAD

**Issue by Mati0x** [1Hive/gardens-v2#130]
- [ ] Forms: Protocol Fee Data from UI to contracts and subgraph
- [ ] Forms: Max Requested Amount error in Funding Proposals. User shuold be able to pass any number below maxRequested
- [ ] Manage support voting data from UI to contracts, member should only be able to supporting with 100% of the weight, not more

**Comment by kamikazebr** [comment]
Still a issue? Cannot find branch, closing
