### ISSUE TITLE
Adding more info Pool Governance component

### ISSUE THREAD

**Issue by Mati0x** [1Hive/gardens-v2#159]
#164 

- [x] new layout to show tokens staked and pool weight of member
- [x] minor upgrade in `Proposal` component to show pool weight % used by proposal supported by  member
- [x] add color reference to member pool weight used = "black text" and each proposal supported pool weight used "blue color"
- [x]  add allPoolWeight used based on member current support to proposals

Implementhing this
![image](https://github.com/1Hive/gardens-v2/assets/691510/dbae9967-6a63-4a87-bb26-10229234c107)

**Comment by kamikazebr** [comment]
@pglavin2 @Mati0x
