### ISSUE TITLE
add strategy button

### ISSUE THREAD

**Issue by Mati0x** [1Hive/gardens-v2#174]
at community level:
- [x]  have new category for pools called: "Pool in Review" / ... those are waiting for council approval. Add banner type with description: "waiting for council approval"

at poolId page:
- [x]  only show  the first section that includes title and description ...etc + badge "pending review from council safe"

**Comment by kamikazebr** [comment]
- Also you need show in some place the status of the strategy been disabled and enabled
- And that its missing in the subgraph too i think @rperez89
