### ISSUE TITLE
Pool Page shows results of CV proposals

### ISSUE THREAD

**Issue by pglavin2** [1Hive/gardens-v2#18]
display all proposal results - progress bars with total conviction, support added/removed, and support needed to pass.

toggle for proposal status (active, passed, cancelled, challenged, blocked)

**Comment by Mati0x** [comment]
Get data for charts from subgraph
 To do:

Funcionalities: ...add !

**Comment by kamikazebr** [comment]
like as #21

**Comment by kamikazebr** [comment]
Fix in #92
