### ISSUE TITLE
Pool Page displays user's points

### ISSUE THREAD

**Issue by pglavin2** [1Hive/gardens-v2#20]
If no wallet connected:  "connect your wallet to see if you have points in this pool"

wallet connected, user has no points:  "support the community covenant to get points in this pool"

wallet connected, user has points not activated:  "you have [# points] to activate in this pool!"

wallet connected, user has activated points: 

- show # of points activated
- show # of points staked in proposals vs. inactive
- show user's deposit amount
- button to deactivate points and get deposit returned

**Comment by Mati0x** [comment]
We need first fix connection problems so we can properly call data . @kamikazebr is on this !!!

**Comment by Mati0x** [comment]
@pglavin2 there is no need is managing all this wallted connectes or buttons disables, until we have the final designs
and also this "button to deactivate points and get deposit returned" ... the activate and deactivate is just for each pool, to be returned the funds is related to the staking membership right ? ...in community page ..? ...no here
