### ISSUE TITLE
Pool Page metrics

### ISSUE THREAD

**Issue by pglavin2** [1Hive/gardens-v2#21]
Display on pool page:

- tokens, $ amount in pool
- tokens, $ amount already funded to proposals
- users with points activated, points staked in active proposals vs. idle points

**Comment by Mati0x** [comment]
Metrics in V-2 are important!, so we should implement first:  ChartBase component that addaps to any chart and recieved any data as well as any chart

**Comment by Mati0x** [comment]
Re define how data is passed to the charts components, taking the data from the contracts

**Comment by kamikazebr** [comment]
in favor of #19
