### ISSUE TITLE
Submiting Communities leads to error but prompts "All ready"

### ISSUE THREAD

**Issue by Corantin** [1Hive/gardens-v2#218]
![image](https://github.com/1Hive/gardens-v2/assets/13890618/20c2910a-ca27-4bed-ad6a-53a87d5b87af)

Steps:
1. Go to a garden on a chain having no strategy
2. Create a new community and fill up the fields
3. Submit

Reproducibility: always

**Comment by kamikazebr** [comment]
It was fixed
