### ISSUE TITLE
Create a new Conviction Voting Strategy / Pool

### ISSUE THREAD

**Issue by pglavin2** [1Hive/gardens-v2#23]
From the community page, option to "Create a New Pool" with a flow to set up the following:

**Strategy Name**
**Strategy Description**
**Strategy Type**
   1.  Grants Pool
   2.  Signaling Prompt (no funding, only signaling proposals)
   3.  Streaming Pool ("coming soon" if not ready for MVP)
**Funding Details**
   - Funding Pool Token
   - Deposit Amount to Activate Points (thinking we'll use the same token as funding pool token so fee can be easily added to Pool)
   - Fee % to community + receiving address (checkbox to add fee to Pool that's "recommended" - fee taken from Deposit)
**Points System**
   1. Fixed - all users get same number of points
   2. Capped - more tokens staked = more points, capped at a maximum
   3. Unlimited - more tokens staked = more points, no cap
   4. Quadratic - points = square root of tokens staked
**CV Parameters**
   - Friendly Parameter setup (Paul still thinking through this)
   - Advanced Settings (set Minimum Conviction, Spending Limit, Conviction Growth half-life, and Minimum Points Activated directly)
   - Proposal Creator Whitelist: upload addresses allowed to create a proposal
   - Voter Whitelist: upload addresses allowed to vote on proposals
   - Deposit Amount to Create a Proposal
   - Deposit Amount to Dispute a Proposal
   - Safe Address that will rule on disputes
   - Amount of time Tribunal has to rule on a dispute + abstain behavior (if no response is proposal blocked or allowed?)

**Deploy!**

**Comment by Mati0x** [comment]
Noted!, this will be possible for late next sprint I assume
