### ISSUE TITLE
Activate governance: disable wiih tooltip on conditions

### ISSUE THREAD

**Issue by Corantin** [1Hive/gardens-v2#235]
![Image](https://github.com/1Hive/gardens-v2/assets/13890618/7942f0e3-e6e8-41b0-87c3-47e3abecc62d)

**Comment by kamikazebr** [comment]
@rperez89

**Comment by Corantin** [comment]
Related #273

**Comment by Corantin** [comment]
This migth be a separated allow list than just passport threshold
