### ISSUE TITLE
Dispute a Proposal

### ISSUE THREAD

**Issue by pglavin2** [1Hive/gardens-v2#24]
Once this process is set in the smart contracts we'll need a flow for users to dispute proposals and have them ruled on by the Tribunal.

**Comment by kamikazebr** [comment]
@kafann @kamikazebr helping contracts

**Comment by pglavin2** [comment]
Closing since we are tracking in this issue:  https://github.com/orgs/1Hive/projects/12/views/1?pane=issue&itemId=54685749
