### ISSUE TITLE
Proposal generated identicon

### ISSUE THREAD

**Issue by Corantin** [1Hive/gardens-v2#255]
To be done in issue #257 
The figma proposal images are too low resolution and we already integrated them in the app:

![Image](https://github.com/1Hive/gardens-v2/assets/13890618/5bd07a2b-0e45-41ce-92ee-067d96768698)

Could be nice to have an identicon that generate an image based on the proposal id:
Ideas: https://drhus.github.io/awesome-identicons/

![Image](https://github.com/1Hive/gardens-v2/assets/13890618/f4dfaf65-10d4-4237-ac1b-dab49eb9d4bf)

![Image](https://github.com/1Hive/gardens-v2/assets/13890618/f5efad8a-d304-4721-91e9-e215e69273f1)

![Image](https://github.com/1Hive/gardens-v2/assets/13890618/eec14d34-4959-4d32-9f6d-f298e1101891)

**Comment by Mati0x** [comment]
We can integrate this issue in #257 maybe what do you think @Corantin ?

**Comment by Corantin** [comment]
Agree but this also include the proposal viee
