### ISSUE TITLE
More components to add

### ISSUE THREAD

**Issue by Mati0x** [1Hive/gardens-v2#259]
In these issue I gonna provide details for what component need to be added as they are used all over the app.
We need a bit further discussion and later divide each addition into it own PR 

Alert dialog: pop up used to alert user for doing very important action:

![Image](https://github.com/1Hive/gardens-v2/assets/94074651/c2913518-559b-4ab6-a3be-67f09c0cd3b0)

Banner: used to give alert to user and some description:

![Image](https://github.com/1Hive/gardens-v2/assets/94074651/680990e3-3029-4e08-8709-d3ef59dce876)

Refactor:
 Modal (delivering if it is similar to alert dialog or not )

**Comment by Corantin** [comment]
https://www.nngroup.com/articles/modal-nonmodal-dialog/
