### ISSUE TITLE
Bug: Back button is overlapped with the content

### ISSUE THREAD

**Issue by Corantin** [1Hive/gardens-v2#261]
![Image](https://github.com/1Hive/gardens-v2/assets/13890618/96ed045f-9140-44c9-acb1-6de1b7199ae1)

Probably should go above the content and not be sticky

**Comment by Lucianosc** [comment]
I will ask Salvador to add it to the designs so we can know how to handle it in smaller screens

**Comment by Corantin** [comment]
He already have a back button on top in the figma. Ut yeah that can be for
small screen only but im on 1080p on my laptop and its pretty much always
overlaping for me

**Comment by Lucianosc** [comment]
Solved in #239
