### ISSUE TITLE
Bug: Proposal page doesnt load

### ISSUE THREAD

**Issue by Corantin** [1Hive/gardens-v2#282]
https://gardens-v2-dev.vercel.app/gardens/421614/0xcc6c8b9f745db2277f7aac1bc026d5c2ea7bd88d/0x9e0ead3bf241734db516a8ecda55bf7c9596540c/pool/356/0x15ac01e5fd499f69ace8299e182fcfd8379f164f-1

Infinite loading

**Comment by Corantin** [comment]
![Image](https://github.com/1Hive/gardens-v2/assets/13890618/cc59d81c-ecf9-49f6-b7e7-61c487ab4e14)

**Comment by Corantin** [comment]
I will do a frontend fix that fallback to zero if status is executed until the backend is fixed

**Comment by Corantin** [comment]
Should we close it ? Looks like an expected behavior from the contracts and #302 is always fixing it from the frontend:
It depends on if we want to display the chart for the frontend.

'''
if (proposal.proposalStatus != StrategyStruct.ProposalStatus.Active) {
            revert ProposalNotActive(proposalId);
        }
'''
![Image](https://github.com/user-attachments/assets/11a268d8-65b1-4eb0-adb4-2ebf8a37bf3d)

**Comment by kamikazebr** [comment]
To be honest the real problem its the function, we should have some getter function that dont do state changes neither revert, but if you can check that in the UI to avoid calling, we can close
