### ISSUE TITLE
Feature: Information-box and Info-icon-tooltip

### ISSUE THREAD

**Issue by Mati0x** [1Hive/gardens-v2#306]
Implement a reusable Information Box component and an Info icon with tooltip functionality to provide users with contextual information across the application. 

- [x] Create reusable Information Box component
- [x] Create reusable Info icon with tooltip
- [x] Integrate both across app or as demand 

Something like this: 

![Image](https://github.com/user-attachments/assets/7e172502-467c-4f99-980d-de2b4d9069f3)

**Comment by Corantin** [comment]
I saw there is some already but they have an explamation point instead of the i :S

**Comment by Mati0x** [comment]
Yeah lets make a component like that, good goss!
