### ISSUE TITLE
Possible! data fetching bug

### ISSUE THREAD

**Issue by Mati0x** [1Hive/gardens-v2#332]
From what we have so far. I seems some data sources are not being loaded and respond as expected. 

**It is mainly data related to member staked**. It might be because some issues are still WIP. 

It is time also to have new contracts being publish, so after certain PRs are merged and new contracts deploy, we can make sure that this is a bug or not. 

So for next sprint we must make sure data is loaded correctly. Specifically this sections:

![Image](https://github.com/user-attachments/assets/0892e12b-4eb5-4ebf-85f1-b22a2e81aff2)

For ever loop in pulling data toast, UI stay forever like this:
![Image](https://github.com/user-attachments/assets/19e21c33-be26-4ade-ba90-f36f53dbecdd)

![Image](https://github.com/user-attachments/assets/d3013c81-91ba-4960-b23f-a7b54d2105a1)

![Image](https://github.com/user-attachments/assets/38000cde-8b62-40c7-8556-d0a76db0de20)

**Comment by Corantin** [comment]
@Mati0x I think we can close this one, it should has been fixed by 

![Image](https://github.com/user-attachments/assets/4cb18a50-935d-4c6c-9fb2-8440caa1f157)
