### ISSUE TITLE
Bug: Pool created with 10 days CV growth displays 6.69 days

### ISSUE THREAD

**Issue by Corantin** [1Hive/gardens-v2#370]
https://gardens-v2-git-beta-1hive.vercel.app/gardens/42161/0x912ce59144191c1204e64559fe8253a0e49e6548/0x309f6cc0602f1842885446693ba612516cb10a48/471

**Comment by Mati0x** [comment]
Need some deep conversation, is it a contracts problem ?

**Comment by Corantin** [comment]
> Need some deep conversation, is it a contracts problem ?

@kamikazebr

**Comment by Corantin** [comment]
The ball is on the contract side
