### ISSUE TITLE
Pool page touchups

### ISSUE THREAD

**Issue by Corantin** [1Hive/gardens-v2#403]
- [x] Consider change from info box to info tip next to governance weight:
![Image](https://github.com/user-attachments/assets/6444e3f4-cc7a-4a41-b4d7-042398cbf434)
mati: not consider this, infoBox is better 

- [x] Consider removing the message "Share it with the community and get support!"
![Image](https://github.com/user-attachments/assets/527b7c9f-44bb-4fc4-8463-0a691600a37d)

- [x] have them in oder desc

**Comment by Mati0x** [comment]
the text before the "create proposal"  button is already fixed in upgrade proposal card #442
