### ISSUE TITLE
Tribunal implementation - Dispute a proposal

### ISSUE THREAD

**Issue by kamikazebr** [1Hive/gardens-v2#75]
### Contract tasks
- [x] #287 
- [x] #290
- [x] #292 
- [x] #293 
- [x] #298 

### UI tasks
- [x] #288
- [x] #289
- [ ] #295 
- [x] #299

**Comment by pglavin2** [comment]
**Basic functions**

Parameters on setup of CV strategy:
- amount deposit to dispute
- length of time Tribunal Safe has to make decision
- default decision if Tribunal Safe doesn't rule in time / abstains

Plus:
- Discord ticket system for 3 parties to communicate (disputer, proposal creator, tribunal)

**Comment by kamikazebr** [comment]
For Fluid Proposals should allow be challenged more than time, becuase it will stop the streaming while its challenged

**Comment by Corantin** [comment]
![Image](https://github.com/1Hive/gardens-v2/assets/13890618/23f753e6-8cb0-45d8-b7b5-544c0403b3a5)

**Comment by Corantin** [comment]
![Image](https://github.com/1Hive/gardens-v2/assets/13890618/123674cc-df90-4e53-88c4-b5cfa458cbda)
