### ISSUE TITLE
General App Fixes

### ISSUE THREAD

**Issue by Mati0x** [1Hive/gardens-v2#80]
Improve the UX with the following :
 -disable register in comm if user has insufficient balance of the gardenToken
 -disable activate points if user is not register in community

Rename and distinguish Grants Pools vs Signaling: find better naming, separate boxes in communityCard

Add protocol Fee and and Community Fee in community card

Add function to manipulate bigNumbers

 Improve decimals in: `CommuntyCard` , `PoolCard`, PoolId page, Proposal page

Upgrade contracts deployment

**Comment by rperez89** [comment]
closed by #82
