### ISSUE TITLE
Deployments on Arbitrum, Optimism, Gnosis Chain, and Polygon Mainnets

### ISSUE THREAD

**Issue by pglavin2** [1Hive/gardens-v2#86]
WE should create a issue for each network chain

- [x] Arbitrum 
- [x] Optimism
- [x] Eth Sepolia

Can be done in another PR

- [ ] ~Gnosis Chain~
- [ ] ~Polygon~

**Comment by kamikazebr** [comment]
was made the multichain script to include Optimism chain.
